### ISSUE TITLE
ssl_check doesnt output exception messages properly

### ISSUE THREAD

**Issue by niallcreech** [ministryofjustice/ops-tools#28]
ssl_check uses exception variables that dont exist for some of its messages 

Traceback (most recent call last):
  File "./reports/ssl_check/ssl_check.py", line 404, in <module>
    check.run()
  File "./reports/ssl_check/ssl_check.py", line 369, in run
    result = self.request_report(host, detailed=True)
  File "./reports/ssl_check/ssl_check.py", line 117, in request_report
    .format(e.code, api_target, e.message))
AttributeError: 'ConnectTimeout' object has no attribute 'code'

**Comment by niallcreech** [comment]
Replaced by new rewrite
